export const BUTTON = [
  { digit: 'AC', operand: true },
  { digit: 'DEL', operand: true },
  { digit: '÷', operand: true },
  { digit: '1', operand: false },
  { digit: '2', operand: false },
  { digit: '3', operand: false },
  { digit: '*', operand: true },
  { digit: '4', operand: false },
  { digit: '5', operand: false },
  { digit: '6', operand: false },
  { digit: '+', operand: true },
  { digit: '7', operand: false },
  { digit: '8', operand: false },
  { digit: '9', operand: false },
  { digit: '-', operand: true },
  { digit: '.', operand: false },
  { digit: '0', operand: false },
  { digit: '=', operand: true },
];
